# Generated by Django 3.1.2 on 2020-12-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201223_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closedbid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=64)),
                ('winner', models.CharField(max_length=64)),
                ('listingid', models.IntegerField()),
                ('winprice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
